--PONEMOS EL NOMBRE DE LA FK QUE TENIAMOS ANTES--
ALTER TABLE colegios_actividades
DROP CONSTRAINT FK_actividades_colegio;

--PONERLO A NULL IMPORTANTE PARA QUE AL BORRAR EL COLEGIO Y LA ACTIVIDAD SE QUEDE VACIA PUES PONEMOS NULL.
ALTER TABLE colegios_actividades
ALTER COLUMN idColegio INT NULL;

--PONEMOS LA NUEVA FOREIGN KEY QUE HEMOS CREADO CON OTRO NOMBRE NUEVO--
ALTER TABLE colegios_actividades
ADD CONSTRAINT FK_colegio_actividades
FOREIGN KEY (idColegio) REFERENCES colegios(idColegio)
ON DELETE SET NULL;